// Generated by gencpp from file talklisten/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TALKLISTEN_MESSAGE_ADDTWOINTS_H
#define TALKLISTEN_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <talklisten/AddTwoIntsRequest.h>
#include <talklisten/AddTwoIntsResponse.h>


namespace talklisten
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace talklisten


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::talklisten::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::talklisten::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::talklisten::AddTwoInts > {
  static const char* value()
  {
    return "talklisten/AddTwoInts";
  }

  static const char* value(const ::talklisten::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::talklisten::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::talklisten::AddTwoInts >
template<>
struct MD5Sum< ::talklisten::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::talklisten::AddTwoInts >::value();
  }
  static const char* value(const ::talklisten::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::talklisten::AddTwoIntsRequest> should match
// service_traits::DataType< ::talklisten::AddTwoInts >
template<>
struct DataType< ::talklisten::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::talklisten::AddTwoInts >::value();
  }
  static const char* value(const ::talklisten::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::talklisten::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::talklisten::AddTwoInts >
template<>
struct MD5Sum< ::talklisten::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::talklisten::AddTwoInts >::value();
  }
  static const char* value(const ::talklisten::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::talklisten::AddTwoIntsResponse> should match
// service_traits::DataType< ::talklisten::AddTwoInts >
template<>
struct DataType< ::talklisten::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::talklisten::AddTwoInts >::value();
  }
  static const char* value(const ::talklisten::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TALKLISTEN_MESSAGE_ADDTWOINTS_H
