// Generated by gencpp from file talklisten/Num.msg
// DO NOT EDIT!


#ifndef TALKLISTEN_MESSAGE_NUM_H
#define TALKLISTEN_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace talklisten
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num1(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num1(0)  {
  (void)_alloc;
    }



   typedef int64_t _num1_type;
  _num1_type num1;





  typedef boost::shared_ptr< ::talklisten::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::talklisten::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::talklisten::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::talklisten::Num > NumPtr;
typedef boost::shared_ptr< ::talklisten::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::talklisten::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::talklisten::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::talklisten::Num_<ContainerAllocator1> & lhs, const ::talklisten::Num_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::talklisten::Num_<ContainerAllocator1> & lhs, const ::talklisten::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace talklisten

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::talklisten::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talklisten::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talklisten::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talklisten::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talklisten::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talklisten::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::talklisten::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ed0120b0616d1b6c77186c64d8cb79d";
  }

  static const char* value(const ::talklisten::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ed0120b0616d1b6ULL;
  static const uint64_t static_value2 = 0xc77186c64d8cb79dULL;
};

template<class ContainerAllocator>
struct DataType< ::talklisten::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "talklisten/Num";
  }

  static const char* value(const ::talklisten::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::talklisten::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num1\n"
;
  }

  static const char* value(const ::talklisten::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::talklisten::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::talklisten::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::talklisten::Num_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TALKLISTEN_MESSAGE_NUM_H
