// Generated by gencpp from file talklisten/PositionResponse.msg
// DO NOT EDIT!


#ifndef TALKLISTEN_MESSAGE_POSITIONRESPONSE_H
#define TALKLISTEN_MESSAGE_POSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace talklisten
{
template <class ContainerAllocator>
struct PositionResponse_
{
  typedef PositionResponse_<ContainerAllocator> Type;

  PositionResponse_()
    : posx(0)
    , posy(0)
    , chr(0)
    , dir()  {
    }
  PositionResponse_(const ContainerAllocator& _alloc)
    : posx(0)
    , posy(0)
    , chr(0)
    , dir(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _posx_type;
  _posx_type posx;

   typedef int64_t _posy_type;
  _posy_type posy;

   typedef uint8_t _chr_type;
  _chr_type chr;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dir_type;
  _dir_type dir;





  typedef boost::shared_ptr< ::talklisten::PositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::talklisten::PositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PositionResponse_

typedef ::talklisten::PositionResponse_<std::allocator<void> > PositionResponse;

typedef boost::shared_ptr< ::talklisten::PositionResponse > PositionResponsePtr;
typedef boost::shared_ptr< ::talklisten::PositionResponse const> PositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::talklisten::PositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::talklisten::PositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::talklisten::PositionResponse_<ContainerAllocator1> & lhs, const ::talklisten::PositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.posx == rhs.posx &&
    lhs.posy == rhs.posy &&
    lhs.chr == rhs.chr &&
    lhs.dir == rhs.dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::talklisten::PositionResponse_<ContainerAllocator1> & lhs, const ::talklisten::PositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace talklisten

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::talklisten::PositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talklisten::PositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talklisten::PositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talklisten::PositionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talklisten::PositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talklisten::PositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::talklisten::PositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cb9c36699476c84f11a338a93242a00";
  }

  static const char* value(const ::talklisten::PositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cb9c36699476c84ULL;
  static const uint64_t static_value2 = 0xf11a338a93242a00ULL;
};

template<class ContainerAllocator>
struct DataType< ::talklisten::PositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "talklisten/PositionResponse";
  }

  static const char* value(const ::talklisten::PositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::talklisten::PositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 posx\n"
"int64 posy\n"
"char chr\n"
"string dir\n"
"\n"
;
  }

  static const char* value(const ::talklisten::PositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::talklisten::PositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posx);
      stream.next(m.posy);
      stream.next(m.chr);
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::talklisten::PositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::talklisten::PositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "posx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.posx);
    s << indent << "posy: ";
    Printer<int64_t>::stream(s, indent + "  ", v.posy);
    s << indent << "chr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chr);
    s << indent << "dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TALKLISTEN_MESSAGE_POSITIONRESPONSE_H
