// Generated by gencpp from file talklisten/Position.msg
// DO NOT EDIT!


#ifndef TALKLISTEN_MESSAGE_POSITION_H
#define TALKLISTEN_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <talklisten/PositionRequest.h>
#include <talklisten/PositionResponse.h>


namespace talklisten
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace talklisten


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::talklisten::Position > {
  static const char* value()
  {
    return "d72baf183df81558beca8e5513a46eef";
  }

  static const char* value(const ::talklisten::Position&) { return value(); }
};

template<>
struct DataType< ::talklisten::Position > {
  static const char* value()
  {
    return "talklisten/Position";
  }

  static const char* value(const ::talklisten::Position&) { return value(); }
};


// service_traits::MD5Sum< ::talklisten::PositionRequest> should match
// service_traits::MD5Sum< ::talklisten::Position >
template<>
struct MD5Sum< ::talklisten::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::talklisten::Position >::value();
  }
  static const char* value(const ::talklisten::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::talklisten::PositionRequest> should match
// service_traits::DataType< ::talklisten::Position >
template<>
struct DataType< ::talklisten::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::talklisten::Position >::value();
  }
  static const char* value(const ::talklisten::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::talklisten::PositionResponse> should match
// service_traits::MD5Sum< ::talklisten::Position >
template<>
struct MD5Sum< ::talklisten::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::talklisten::Position >::value();
  }
  static const char* value(const ::talklisten::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::talklisten::PositionResponse> should match
// service_traits::DataType< ::talklisten::Position >
template<>
struct DataType< ::talklisten::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::talklisten::Position >::value();
  }
  static const char* value(const ::talklisten::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TALKLISTEN_MESSAGE_POSITION_H
