(cl:defpackage talklisten-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "POSITION"
   "<POSITION-REQUEST>"
   "POSITION-REQUEST"
   "<POSITION-RESPONSE>"
   "POSITION-RESPONSE"
  ))

